[package]
name = "cryptographic_id"
version = "0.1.0"
authors = ["Simon Brand <simon.brand@postadigitale.de>"]
edition = "2021"

[dependencies]
base64 = "0.13.1"
ed25519-dalek = "1.0.1"
prost = "0.11.0"
qrcode = { version = "0.12.0", default-features = false }
rand = "0.7.0"

[build-dependencies]
prost-build = "0.11.1"
