[package]
name = "cryptographic-id-rs"
version = "0.1.6"
authors = ["Simon Brand <simon.brand@postadigitale.de>"]
edition = "2021"

[dependencies]
base64 = "0.13.1"
ed25519-dalek = "1.0.1"
prost = "0.11.9"
qrcode = { version = "0.12.0", default-features = false }
rand = "0.7.3"

[build-dependencies]
prost-build = "0.11.3"
