
# cargo-vet config file

[cargo-vet]
version = "0.6"

[imports.bytecodealliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/rust-crate-audits/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[[exemptions.aho-corasick]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.anyhow]]
version = "1.0.72"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.byteorder]]
version = "1.4.3"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.0.81"
criteria = "safe-to-deploy"

[[exemptions.checked_int_cast]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek]]
version = "3.2.1"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.ed25519]]
version = "1.4.1"
criteria = "safe-to-deploy"

[[exemptions.ed25519-dalek]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.either]]
version = "1.9.0"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.fastrand]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.fixedbitset]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.1.16"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "1.9.3"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.10.5"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.147"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.19"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.multimap]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.16.0"
criteria = "safe-to-deploy"

[[exemptions.petgraph]]
version = "0.6.3"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.prettyplease]]
version = "0.1.25"
criteria = "safe-to-deploy"

[[exemptions.prost]]
version = "0.11.9"
criteria = "safe-to-deploy"

[[exemptions.prost-build]]
version = "0.11.9"
criteria = "safe-to-deploy"

[[exemptions.prost-derive]]
version = "0.11.9"
criteria = "safe-to-deploy"

[[exemptions.prost-types]]
version = "0.11.9"
criteria = "safe-to-deploy"

[[exemptions.qrcode]]
version = "0.12.0"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.32"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.rand_hc]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.9.1"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "0.38.6"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.181"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.9.9"
criteria = "safe-to-deploy"

[[exemptions.signature]]
version = "1.6.4"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.109"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.28"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.7.0"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.11"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.9.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.which]]
version = "4.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.48.1"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.zeroize_derive]]
version = "1.4.2"
criteria = "safe-to-deploy"
