#!/bin/bash
DIR="/etc/cryptographic_id/initramfs"

build() {
	add_binary cat
	add_binary date
	add_binary mkdir
	add_binary mount
	add_binary rm
	add_binary systemd-escape
	add_binary umount
	add_binary "/usr/lib/cryptographic_id/cryptographic-id-rs"
	add_file "/usr/lib/cryptographic_id/initramfs_helper"
	add_file "/usr/lib/cryptographic_id/show_identities"
	add_dir /tmp/cryptographic_id
	if [ "$(find "${DIR}" -perm -o=r)" != "" ]; then
		error "ERR: There are world readable files in ${DIR}\\n"
		exit 1
	fi
	add_full_dir "${DIR}"
	font="$(tr -d ' \t\n' < "${DIR}/font")"
	printf "%s" "${font}" > "${BUILDROOT}/${DIR}/font"
	if [ "${font}" != "" ]; then
		add_file "/usr/share/kbd/consolefonts/${font}"*
		add_binary setfont
	fi
	if [ -n "$(ls -A "${DIR}/age")" ]; then
		add_binary "age"
	fi
	if [ -n "$(ls -A "${DIR}/cryptsetup")" ]; then
		add_binary "/usr/lib/systemd/systemd-cryptsetup"
		add_module 'dm-crypt'
		add_all_modules '/crypto/'
	fi
	if [ -n "$(ls -A "${DIR}/tpm2")" ]; then
		add_binary tpm2_createprimary
		add_binary tpm2_flushcontext
		add_binary tpm2_load
		add_binary tpm2_policypcr
		add_binary tpm2_sign
		add_binary tpm2_startauthsession
		add_checked_modules '/drivers/char/tpm/'
	fi
	if type add_systemd_unit &> /dev/null; then
		add_systemd_unit cryptographic_id.service
		add_systemd_unit cryptographic_id_helper@.service
		cat <<EOF | add_systemd_drop_in initrd-switch-root.service cryptographic_id
[Unit]
After=cryptographic_id.service
Wants=cryptographic_id.service
EOF
		cat <<EOF | add_systemd_drop_in systemd-cryptsetup@.service cryptographic_id
[Unit]
After=cryptographic_id.service
Wants=cryptographic_id.service
EOF
	else
		error "ERR: non-systemd variant not supported"
		exit 1
	fi
}

help() {
	cat <<HELPEOF
This hooks prints cryptographic identities from unencrypted,
age-encrypted or tpm2+pin encrypted files.
HELPEOF
}
