on: [push, pull_request]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - run: git submodule update --init --recursive
      - run: sudo apt-get update
      - run: sudo apt-get --yes install protobuf-compiler cargo shellcheck
      - run: shellcheck usr/lib/cryptographic_id/* usr/bin/*
             usr/lib/initcpio/install/cryptographic-id
             usr/lib/dracut/modules.d/90cryptographic-id/module-setup.sh
      - run: cargo test --workspace --verbose --locked
