on: [push, pull_request]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - run: git submodule update --init --recursive
      - run: sudo apt-get update
      - run: sudo apt-get --yes install protobuf-compiler cargo shellcheck
             dbus-daemon
             swtpm swtpm-tools tpm2-abrmd tpm2-tools
             libtss2-dev libtss2-tcti-swtpm0 libtss2-tcti-tabrmd0
      - run: shellcheck usr/lib/cryptographic_id/* usr/bin/*
             usr/lib/initcpio/install/cryptographic-id
             usr/lib/dracut/modules.d/90cryptographic-id/module-setup.sh
      - run: dbus-run-session bash tests/run_test.sh
